### ISSUE TITLE
 Matching only one key pair of many

### ISSUE THREAD

**Issue by classic0** [DanielHreben/jest-matcher-specific-error#1]
Thanks for an awesome matcher, it's just about of what I was looking for and generally it serves my purpose. But since I have most of the tests written having the Error constructor in mind, the most important notion of identifying the correct error lies in it's message. 
Could it be possible to match only a selected key, as could be 'message' or any other instead of passing the entire object into the matcher?

Cheers

**Comment by DanielHreben** [comment]
So, you want to check error class and message, but nothing else? 
Btw, If you want to check only message or only error class it's possible with standard matchers.

**Comment by classic0** [comment]
If I have an error object constructed so:
```throw {
    code: 2,
    message: 'Custom err message'
} ```

And I am thinking if I could match only the message of that object, it would be excellent.

**Comment by DanielHreben** [comment]
In this case, you can use standard matches:
```typescript
  expect(yourFunction).toThrowError(mesage);
  expect(yourFunction).toThrowErrorMatchingInlineSnapshot();
```

**Comment by classic0** [comment]
I can confirm. Many thanks for the help!
